name: authpass_cloud_backend

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  meta: ^1.8.0
  uuid: ^3.0.6
  logging: ^1.2.0
  logging_appenders: ^1.2.0+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  postgres: ^2.4.5
  collection: ^1.16.0
  quiver: ^3.2.1
  args: ^2.4.2
  checked_yaml: ^2.0.1
  http: ^1.2.0
  clock: ^1.1.1
  mailer: ^6.0.1
  yaml: ^3.1.1
  enough_mail: ^2.1.6
  neat_periodic_task: ^2.0.0
  crypto: ^3.0.3
  smtpd:
    path: ../../deps/smtpd.dart

  shelf: ^1.4.1
  openapi_base: ^1.1.0+3
  authpass_cloud_shared:
    path: ../authpass_cloud_shared
  postgres_utils:
    path: ../../deps/postgres_utils.dart

  # besticon
  html: ^0.15.0
  dartx: ^1.1.0
  image: ^3.2.0
#  image:
#    git:
#      url: https://github.com/authpass/image.git
#      ref: 04bed8d246ef90e3d4f49b12f9df2066f5df7a22

dev_dependencies:
  test: ^1.21.3
  mockito: ^5.2.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.1
  faker: ^2.1.0

dependency_overrides:
  # Because enough_mail >=2.1.6 depends on intl ^0.19.0 and mailer >=6.0.0 depends on intl >=0.17.0 <0.19.0, enough_mail >=2.1.6 is incompatible with mailer >=6.0.0.
  intl: ^0.19.0
#  openapi_base:
#    path: /Users/herbert/dev/openapi_dart/packages/openapi_base
#  mailer:
#    path: ../../deps/mailer

#dependency_overrides:
#  openapi_base:
#    path: ../../deps/openapi_dart/packages/openapi_base
#  quiver: ^2.1.3
#  json_annotation: ^3.0.1
#  openapi_base: ^0.1.5+1
#  freezed_annotation: ^0.11.0
#  dartx: ^0.5.0
#  crypto: ^2.1.0
#  intl: ^0.16.1
#  logging: ^1.0.0
#  http: ^0.12.2
#  dio: ^3.0.0
#  enough_mail:
#    git:
#      url: https://github.com/authpass/enough_mail.git
#      ref: 51239305f89cec75843ad873f73f7a7758823ef0
#  source_gen: ^1.0.0
