name: authpass_cloud_backend

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  uuid: ^2.1.0
  logging: ^0.11.4
  logging_appenders: ^0.4.2+3
  freezed_annotation: ^0.11.0
  json_annotation: ^3.0.1
  pedantic: ^1.9.0
  postgres: ^2.1.1
  quiver: ^2.1.3
  args: ^1.6.0
  checked_yaml: ^1.0.2
  http: ^0.12.1
  clock: ^1.0.1
  mailer: ^3.0.4
  yaml: ^2.2.1

  openapi_base:
    path: ../../deps/openapi_dart/packages/openapi_base
  authpass_cloud_shared:
    path: ../authpass_cloud_shared

dev_dependencies:
  test: ^1.15.1
  mockito: ^4.1.1
  build_runner: ^1.10.0
  freezed: ^0.11.2
  json_serializable: ^3.3.0

