version: '3'
services:
  pgdb:
    # postgres:12.3
    image: postgres@sha256:222c12ec1601f38cee2c84fd044756e32815cf11ce36151735c37cb4ead60855
    ports: ##REMOVELINE
      - 5432:5432 ##REMOVELINE
    environment:
      POSTGRES_USER: authpass
      POSTGRES_PASSWORD: blubb
      POSTGRES_DB: authpass
    volumes:
      - ./_data/pgdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./_data/pgdb/data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 30
        window: 120s
      placement:
        constraints: [node.role == manager]
    stop_grace_period: 60s

