name: authpass_cloud_shared

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  openapi_base: ^1.0.0

dev_dependencies:
  openapi_code_builder:
    path: ../../deps/openapi_dart/packages/openapi_code_builder
  build_runner: ^2.0.6
  json_serializable: ^5.0.0
  pedantic: ^1.11.1

dependency_overrides:
  open_api_forked:
    path: ../../deps/openapi_dart/deps/open-api-dart
  openapi_base:
    path: ../../deps/openapi_dart/packages/openapi_base
