name: authpass_cloud_shared

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  openapi_base: ^0.2.0

dev_dependencies:
  openapi_code_builder:
    path: ../../deps/openapi_dart/packages/openapi_code_builder
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  pedantic: ^1.11.0

dependency_overrides:
  open_api_forked:
    path: ../../deps/openapi_dart/deps/open-api-dart
  openapi_base:
    path: ../../deps/openapi_dart/packages/openapi_base
