name: authpass_cloud_shared

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  openapi_base: ">=1.0.1 <3.0.0"
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  openapi_code_builder:
    path: ../../deps/openapi_dart/packages/openapi_code_builder
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^4.0.0
#
#dependency_overrides:
#  open_api_forked:
#    path: ../../deps/openapi_dart/deps/open-api-dart
#  openapi_base:
#    path: ../../deps/openapi_dart/packages/openapi_base
#  codable_forked:
#    path: ../../deps/openapi_dart/deps/dart-codable
