name: authpass_cloud_shared

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  openapi_base: ">=1.0.1 <2.0.0"
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  openapi_code_builder:
    path: ../../deps/openapi_dart/packages/openapi_code_builder
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0
#
#dependency_overrides:
#  open_api_forked:
#    path: ../../deps/openapi_dart/deps/open-api-dart
#  openapi_base:
#    path: ../../deps/openapi_dart/packages/openapi_base
#  codable_forked:
#    path: ../../deps/openapi_dart/deps/dart-codable
