name: build backend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: create build number
      id: buildnumber
      env:
        GIT_AUTHOR_NAME: 'Github Action CI'
        GIT_AUTHOR_EMAIL: 'herbert.github.ci@codeux.design'
        GIT_COMMITTER_NAME: 'Github Action CI'
        GIT_COMMITTER_EMAIL: 'herbert.github.ci@codeux.design'
      run: |
        buildnumber=$(curl -s https://raw.githubusercontent.com/hpoul/git-buildnumber/v1.0/git-buildnumber.sh | bash /dev/stdin generate)
        echo "::set-output name=buildnumber::$buildnumber"
    - name: docker build
      run: cd docker && docker-compose build backend
    - name: docker login and push
      run: |
        echo '${{ secrets.CONTAINER_ACCESS_TOKEN }}' | docker login https://containers.pkg.github.com -u ${{ secrets.CONTAINER_USER }} --password-stdin
        cd docker && docker-compose push backend
    - name: extract executable from image
      run: |
        image=$( docker create containers.pkg.github.com/authpass/authpass-backend )
        docker cp ${image}:/authpass_backend.exe .
        docker rm ${image}
    - uses: actions/upload-artifact@v2
      with:
        name: auhpass_backend_${{ steps.buildnumber.outputs.buildnumber }}
        path: authpass_backend.exe
